[build]
  command = "npm run build"
  publish = "dist/public"
  environment = { NODE_VERSION = "20" }

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 